### PR TITLE
Update OSX bindings to support caps-lock

### PR DESCRIPTION
**Pull request by fullybaked**
Sorry for the messing around. This PR is correct and adds the caps-lock functionality to the OSX bindings.

### CODE REVIEW

**Comment by binaryphile** [comment]
Thanks!

By the way, I'm looking for testimonials on what Minimak is like as a user.  Would you be inclined to tell me about your experience so far?

**Comment by fullybaked** [comment]
Sorry to say I am back to qwerty.  I never took to the changed key layout quite as well as I thought, even after ramping up through the 3 stages over a 4 month period.  

After spending the better part of this year learning Vim and all its key bindings I doubt I'll give an alternate keyboard layout a try for a while.  

I'm happy to maintain the OSX bindings if any other issues crop up, but I'm no longer a user.

**Comment by binaryphile** [comment]
Ah well, thanks for the feedback, and for fixing the keymappings for a
layout you don't even use any more!

Just so you know, I recommend the 8-key layout for most people since it's
closer to qwerty and has bang for the buck while still accomplishing
something.  Not that it matters, but there you go.

Cheers.

**Comment by fullybaked** [comment]
I'll keep that recommendation in mind if I give the switch another try

Thanks.

> Ted Lilley mailto:notifications@github.com
> 9 September 2013 17:15
> Ah well, thanks for the feedback, and for fixing the keymappings for a
> layout you don't even use any more!
> 
> Just so you know, I recommend the 8-key layout for most people since it's
> closer to qwerty and has bang for the buck while still accomplishing
> something. Not that it matters, but there you go.
> 
> Cheers.
>

**Pull request merged**
